on:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of the image to build'
        required: true
        type: string
      fedora-version:
        description: 'Fedora version to build'
        required: true
        type: string
      git-tag:
        description: 'Git tag to build'
        required: true
        type: string
      kickstart-file-path:
        description: 'Path to the kickstart file'
        required: true
        type: string

env:
  EVERYTHING_INSTALLER_URL: https://download.fedoraproject.org/pub/fedora/linux/releases/${{ inputs.fedora-version }}/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-${{ inputs.fedora-version }}.iso

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container: fedora:latest

    env:
      ISO_FILENAME: ${{ inputs.image-name }}-${{ inputs.fedora-version }}.iso
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-tag }}

      - name: Pull Fedora Everything Installer ISO
        run: |
          mkdir -p /tmp/iso
          curl -L $EVERYTHING_INSTALLER_URL -o Fedora-Everything-netinst-x86_64.iso

      - name: Install Dependencies
        run: |
          dnf install -y lorax

      - name: Build ISO
        run: |
          ls -la
          echo "PWD: $PWD"
          mkksiso --ks ${{ inputs.kickstart-file-path }} Fedora-Everything-netinst-x86_64.iso ${{ env.ISO_FILENAME }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.image-name }}-${{ inputs.fedora-version }}
          path: |
            ${{ inputs.image-name }}-${{ inputs.fedora-version }}.iso

  publish-iso:
    needs: build-iso
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-tag }}

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.image-name }}-${{ inputs.fedora-version }}.iso

      - name: Attach Artifact to Release
        run: |
          echo "Publishing ${{ inputs.image-name }}-${{ inputs.fedora-version }}.iso"
          gh release upload ${{ inputs.git-tag }} ${{ inputs.image-name }}-${{ inputs.fedora-version }}.iso
